services:
  tasklocal-db:
    image: postgis/postgis:16-3.4
    container_name: tasklocal-db
    restart: always
    environment:
      POSTGRES_USER: tasklocal
      POSTGRES_PASSWORD: Baha8547
      POSTGRES_DB: tasklocal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  tasklocal-api:
    build: .
    container_name: tasklocal-api
    restart: always
    depends_on:
      - tasklocal-db
    env_file:
      - .env
    ports:
      - "8000:8000"
    working_dir: /app
    command: >
      sh -c "PYTHONPATH=/app gunicorn app.main:app
      -k uvicorn.workers.UvicornWorker
      -w 4
      -b 0.0.0.0:8000"

  dispatch-worker:
    build: .
    container_name: dispatch-worker
    restart: always
    depends_on:
      - tasklocal-db
    env_file:
      - .env
    working_dir: /app
    command: >
      sh -c "PYTHONPATH=/app python -m app.workers.dispatch_worker"

volumes:
  postgres_data: